project:
  type: website
  render:
  - "01-cleaning.qmd"
  - "02-analysis.qmd"

website:
  title: "Austin Weather Analysis"
  sidebar:
    contents:
      - href: index.qmd
        text: Home
      - auto: "index.qmd"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    df-print: paged
    code-overflow: wrap
